CREATE TABLE IF NOT EXISTS clientes_import_jobs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    db_host VARCHAR(191) NOT NULL,
    db_name VARCHAR(191) NOT NULL,
    db_user VARCHAR(191) NOT NULL,
    db_password VARCHAR(191) NOT NULL,
    m3u_url TEXT NOT NULL,
    m3u_file_path TEXT DEFAULT NULL,
    api_token CHAR(64) NOT NULL,
    status ENUM('queued','running','done','failed') NOT NULL DEFAULT 'queued',
    progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
    message TEXT DEFAULT NULL,
    total_added INT UNSIGNED DEFAULT NULL,
    total_skipped INT UNSIGNED DEFAULT NULL,
    total_errors INT UNSIGNED DEFAULT NULL,
    client_ip VARCHAR(45) DEFAULT NULL,
    client_user_agent VARCHAR(255) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    started_at DATETIME DEFAULT NULL,
    finished_at DATETIME DEFAULT NULL,
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
